"""add_age_to_farmers

Revision ID: 2da43bab8b6c
Revises: 9d3895ed64d3
Create Date: 2026-04-18 00:25:25.413177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2da43bab8b6c'
down_revision: Union[str, Sequence[str], None] = '9d3895ed64d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmers', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farmers', 'age')
    # ### end Alembic commands ###
